### PR TITLE
1.0.3

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@mdraw and @omry please review and merge.

**Comment by omry** [comment]
I am not a maintainer so I can't merge this.

I am expecting one issue that you didn't seem to have fixed, but somehow things are passing anyway:
running pip install on a directory is building the parser with antlr, and this requires an installed java.
I didn't see that you added it anyway and this makes me wonder if it's installing properly.

Also, looking at the checks - I did not see where the tests are actually running. Can you send me a link to the output showing the installation and the output showing the tests?

**Comment by hadim** [comment]
A JRE is actually installed **only during the build** step by installing `antlr` (that depends on java). The parser is only used during the build that why the `run` section only contains the runtime antlr package.

You can check the log of the tests at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=234789&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1110

**Comment by hadim** [comment]
Should I add you as a maintainer of this repo @omry since you're also a Hydra dev?

ping @conda-forge/help-python: can you review this PR, please? I want to be sure the python constraints I put are ok.

**Review by beckermr — COMMENTED** [review]
python constraints look fine

**Comment by omry** [comment]
@hadim , 
1. great about antlr, we only need java during the creation of the package. not at runtime.
2. you can add me but I do not have cycles to maintain this package so it would be great if you take over.

**Review by mdraw — APPROVED** [review]

**Comment by hadim** [comment]
@mdraw only you can merge this.

**Comment by hadim** [comment]
FYI: I added myself as a maintainer.

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by mdraw** [comment]
I'm sorry for the delay. I'm currently not using hydra, so I'm certainly not suited as the only maintainer here. @hadim thanks a lot for stepping in and making this PR. Should I merge it in the current state?

**Comment by hadim** [comment]
yes, you can merge (and no problem for the delay of course!).

**Pull request merged**
